name: Markdown formatting

on:
  push:
    branches:
      - main

jobs:
  format-markdown:
    name: Format Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath

      - name: Install mdformat and plugins
        run: |
          pipx install mdformat
          pipx inject mdformat mdformat-gfm mdformat-frontmatter mdformat-footnote mdformat-gfm-alerts

      - name: Format Markdown files
        run: |
          mdformat .

      - name: Commit changes and push if any
        run: |
          git config --global user.name "Simon Tran"
          git config --global user.email "simontran192@gmail.com"
          git add .
          git commit -m "Apply mdformat formatting"
          git push
