name: Markdown formatting

on:
  push:
    branches:
      - main

jobs:
  format-markdown:
    name: Format Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pipx
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath

      - name: Install mdformat and plugins
        run: |
          pipx install mdformat
          pipx inject mdformat mdformat-gfm mdformat-frontmatter mdformat-footnote mdformat-gfm-alerts

      - name: Format Markdown files
        run: |
          mdformat .
